-- Creación de la tabla de animales si no existe
CREATE TABLE IF NOT EXISTS animals (
    slug VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    "scientificName" VARCHAR(255),
    description TEXT,
    status VARCHAR(255),
    "imageURL" VARCHAR(255),
    habitat TEXT,
    "dataAiHint" VARCHAR(255)
);

-- Creación de la tabla de fundaciones si no existe
CREATE TABLE IF NOT EXISTS foundations (
    slug VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    mission TEXT,
    location VARCHAR(255),
    contact VARCHAR(255),
    "imageURL" VARCHAR(255),
    "dataAiHint" VARCHAR(255),
    "foundationActivities" TEXT,
    lat NUMERIC,
    lng NUMERIC,
    "ofcWebsite" VARCHAR(255)
);

-- Limpieza de datos existentes para evitar duplicados al ejecutar el script múltiples veces
TRUNCATE TABLE animals, foundations RESTART IDENTITY;

-- Inserción de datos en la tabla de animales
INSERT INTO animals (slug, name, "scientificName", description, status, "imageURL", habitat, "dataAiHint") VALUES
('caucel', 'Caucel', 'Felis wiedii', 'El caucel es un felino del tamaño de un gato grande, con cuerpo robusto y cola muy larga. Su pelaje es gris mate con manchas negras bordeadas, y tiene orejas negras con una mancha blanca. Es ágil, nocturno y a veces duerme en árboles durante el día.', 'Mayormente extinto', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/caucel.jpg?alt=media&token=ebe188af-4d67-4557-9849-3e48b1e8412c', 'zonas boscosas', 'caucel'),
('caucel-tigrillo', 'Caucel Tigrillo', 'Leopardus tigrina', 'El caucel o tigrillo es un felino pequeño, similar en tamaño a un gato doméstico. Tiene el lomo grisáceo con manchas en forma de rosetas, el pecho y vientre blanquecinos con manchas oscuras, y ojos amarillentos. Es de hábitos nocturnos, por lo que se sabe poco sobre él. Aunque es principalmente terrestre, también trepa bien los árboles.', 'Vulnerable', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/caucel-tigrillo.jpg?alt=media&token=a427d5bc-4164-46ab-8b25-35ce9a30d1a3', 'Ámbito de distribución pequeño, centro de Costa Rica', 'caucelTigrillo'),
('chancho-de-monte', 'Chancho de monte', 'Tayassu pecari', 'El chancho de monte es un animal parecido a un cerdo, con cuerpo robusto, pelaje grisáceo y áspero, cabeza grande, patas y cola cortas. Su nariz, labios y mejillas son blancos. Mide unos 125 cm y pesa alrededor de 40 kg, sin diferencia de tamaño entre machos y hembras. Ante el ataque de perros cazadores, se defienden en grupo, atacando en parejas y luego regresando a la manada.', 'Mayormente extinto', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/chancho-monte.jpg?alt=media&token=def1096b-4286-4a6f-9ee2-95bb073b6fa1', 'Parque Nacional Tortuguero y Parque Nacional Corcovado', 'chanchoDeMonte'),
('danta', 'Danta', 'Tapirus bairdii', 'La danta es el mamífero silvestre más grande de Costa Rica, con cuerpo robusto, patas fuertes y pezuñas grandes. Su pelaje es café oscuro en el dorso y claro en el vientre, y las crías tienen manchas blancas. Posee un labio superior alargado y flexible, similar a una trompa. Pesa entre 150 y 300 kg. Es tímida y difícil de ver, pero se mueve ágilmente por senderos en el bosque. Puede atacar si percibe una amenaza hacia sus crías.', 'Vulnerable', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/Danta.jpg?alt=media&token=ef830548-ddd6-434e-9e6f-07110e28d15c', 'Reservas y Parques Nacionales, parece ocupar bosques vírgenes para vivir', 'Danta'),
('jaguar', 'Jaguar', 'Panthera onca', 'Este animal, el carnívoro más grande del país, tiene cuerpo robusto, patas cortas y musculosas con fuertes garras, cola corta y orejas pequeñas y redondas. Los machos pesan entre 64 y 100 kg, y las hembras entre 45 y 80 kg. Su pelaje es amarillo en el dorso y blanco en el vientre, con manchas negras en forma de rosetas; algunos ejemplares son completamente negros. Es astuto, desconfiado, con excelente vista y olfato, y el macho ruge por las noches, especialmente en época de reproducción.', 'Vulnerable', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/jaguar.jpg?alt=media&token=014a38aa-8030-4b18-a6f9-96ee8de8d08e', 'Fronteras entre Costa Rica y Nicaragua, Parques Nacionales', 'jaguar'),
('leon-brenero', 'León Breñero', 'herpailurus yaguaroundi', 'Este felino, del tamaño de un gato doméstico pero con cuerpo más largo, patas cortas y una cola muy larga, presenta coloración café rojiza o negro grisáceo. Es esbelto, ágil para trepar y el más activo durante el día entre los felinos del país.', 'Vulnerable', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/Bre%C3%B1ero.jpg?alt=media&token=c7d3ab02-37ed-492f-b470-7f67853511f0', 'Bosques vírgenes y por su adaptación, en plantaciones de caña de azúcar', 'LeonBreñero o Leonmiquero'),
('manati', 'Manatí', 'Trichechus manatus', 'El manatí es un mamífero acuático grande, que pesa entre 200 y 600 kilos. Tiene patas delanteras transformadas en remos, carece de patas traseras y su cola es una aleta aplanada que usa para nadar. No tiene cuello visible, sus ojos son pequeños y redondos, y posee labios carnosos que cuelgan a los lados de la boca.', 'Muy vulnerable', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/manati.jpg?alt=media&token=16039c36-38e8-4480-9fc7-8749b93ae25d', 'Reservas Nacionales, solía habitar en ríos', 'manati'),
('manigordo', 'Manigordo', 'Leopardus pardalis', 'Este mamífero de tamaño mediano tiene cabeza pequeña, cola corta y pelaje gris mate con manchas café oscuro bordeadas de negro. Las manchas del dorso y cuello son alargadas, y la cola tiene manchas negras con la punta completamente negra. Las orejas son negras con una gran mancha blanca. Puede pesar hasta 12 kilos. Es nocturno y descansa durante el día en lo alto de los árboles. Se conoce poco sobre su reproducción en el país.', 'Muy vulnerable', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/manigordo.jpg?alt=media&token=ed0999cf-5bd1-4a45-84c3-4674e426e616', 'Grandes zonas boscosas, parques nacionales y reservas naturales.', 'manigordo'),
('mono-ardilla', 'Mono ardilla', 'Saimiri oerstedii', 'Es el mono más pequeño de los que habitan en los bosques del país. Mide unos 75 cm en total, de los cuales 40 cm corresponden a su larga cola prensil, de color oscuro. Su pelaje es amarillento rojizo con negro alrededor de la cara.', 'Muy vulnerable', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/mono-ardilla.jpg?alt=media&token=3c17330e-6dfc-4522-a45e-fe4bb1e5a99a', 'parques nacionales o al sur del país.', 'Mono ardilla'),
('mono-cariblanco', 'Mono Cariblanco', 'Cebus capucinus', 'El mono cariblanco, también llamado mono capuchino, tiene pelaje crema o amarillento en la cara, cuello, pecho, hombros y parte de los brazos, y el resto del cuerpo es negro. Su cara es rosada y tiene una cola prensil negra, más larga que su cuerpo. Mide unos 45 cm (sin contar la cola) y pesa entre 1,4 y 4,3 kg, siendo los machos más grandes. Es diurno, vive en grupos ruidosos de más de 30 individuos y busca alimento en varios niveles del bosque.', 'Muy vulnerable', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/cariblanco.jpeg?alt=media&token=d7af2283-19c7-40ea-8470-dda2bb011254', 'parques nacionales o en bosques tropicales secos o húmedos.', 'Mono cariblanco'),
('mono-congo', 'Mono Congo', 'Alowatta palliata', 'Este mamífero tiene la cabeza grande y, en los machos adultos, una barba sedosa y prominente. Su cuerpo es pesado y compacto, mide entre 60 y 62 cm, y pesa entre 15 y 25 libras. Su pelaje varía de negro brillante a café rojizo. Es fácilmente reconocible por sus fuertes bramidos, generados por un hueso hioides especial que funciona como caja de resonancia. Durante las noches frías, las manadas se agrupan para mantenerse calientes y al amanecer se dispersan en busca de alimento.', 'Vulnerable', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/congo.jpeg?alt=media&token=b7a983d7-9be2-4797-bd0a-410183709a6f', 'Bosques vírgenes, pasan su vida en la copa de los árboles.', 'Mono congo'),
('mono-arana', 'Mono Araña', 'Ateles geoffroyi', 'El mono araña tiene cabeza pequeña, cuerpo delgado, extremidades largas y una cola más larga que el cuerpo y la cabeza juntos. Puede pesar un poco más de 8 kilos. Su pelaje varía entre rubio, rojizo y casi negro, según la raza. Es diurno, completamente arbóreo y se desplaza ágilmente entre las ramas usando sus extremidades largas y su cola prensil.', 'Muy vulnerable', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/mono-ara%C3%B1a.jpeg?alt=media&token=b18a6ea1-a96e-4b20-8052-cdc298219f6a', 'Todos los bosques, en parques Nacionales y reservas actualmente', 'Mono araña'),
('oso-caballo', 'Oso caballo', 'Myrmecophaga tridactyla', 'Este animal, de hábitos exclusivamente terrestres, se reconoce por su hocico largo en forma de tubo y su espesa cola similar a la de un caballo. Tiene patas cortas, orejas y ojos pequeños, y una lengua larga y cilíndrica. Pesa entre 25 y 30 kilos. Para defenderse, se levanta sobre sus patas traseras y muestra sus fuertes garras delanteras.', 'Mayormente extinto', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/Oso-caballo.jpg?alt=media&token=1d3099a8-d141-4f52-8433-b0e20e55fdf5', 'Habita en parques nacionales.', 'Oso caballo'),
('puma', 'Puma', 'Puma concolor', 'Este felino grande tiene patas y cola muy largas. Su pelaje es pardo amarillento, con el mentón, garganta, mejillas y pecho blancos. Las crías tienen manchas oscuras hasta los 3 o 4 meses. En raras ocasiones, puede aparecer un ejemplar negro. Es un animal solitario y polígamo.', 'Muy vulnerable', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/puma.jpeg?alt=media&token=8110a739-b256-41df-8ddf-af3d21572580', 'Areas boscosas, parques nacionales y reservas ecológicas.', 'Puma');

-- Inserción de datos en la tabla de fundaciones
INSERT INTO foundations (slug, name, mission, location, contact, "imageURL", "dataAiHint", "foundationActivities", lat, lng, "ofcWebsite") VALUES
('rescate-wildlife-rescue-center', 'Rescate Wildlife Rescue Center', 'Proteger, conservar y restaurar la biodiversidad del país mediante el rescate, la rehabilitación, la liberación de animales silvestres y la reproducción de especies amenazadas. Promover la educación medioambiental y el cuidado de la fauna silvestre que no puede ser liberada.', 'La Garita, Alajuela, Costa Rica', 'info@rescatewildlife.org', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/wildlife.webp?alt=media&token=d5c1ec93-c7b4-4bd5-b08c-7c4dd6aac7f5', 'Wildlifesanctuary', 'Rescate Wildlife Rescue Center – Zoave es el mayor centro de rescate de vida silvestre en América Central, rehabilitando y liberando a más de 3.000 animales al año. Cuenta con el único hospital para fauna silvestre en Costa Rica, programas de cría, educación y reservas privadas para liberación y reforestación. Es una organización sin fines de lucro dedicada a proteger la biodiversidad.', 10.012344426769621, -84.27560494037206, 'https://rescatewildlife.org/es'),
('refugio-animal-de-costa-rica', 'Refugio Animal de Costa Rica', 'La misión del Refugio Animal de Costa Rica es rescatar, rehabilitar y liberar animales silvestres de vuelta a su hábitat natural cuando están listos para sobrevivir. Para aquellos animales que no pueden ser devueltos a la vida silvestre, proporcionan el mejor cuidado y espacios donde puedan vivir felices y saludables, convirtiéndolos en embajadores educativos. Su herramienta de conservación más fuerte es educar a las próximas generaciones sobre cómo respetar la vida silvestre y el equilibrio de la naturaleza.', 'Santa Ana, San José, Costa Rica', 'En la página', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/RefugioAnimalSantaAnaa.avif?alt=media&token=871499ce-c172-4894-807a-ae7601106050', 'Refugio Animal, Santa ana', 'Refugio Animal de Costa Rica es un refugio sin fines de lucro ubicado en Santa Ana que se especializa en el rescate, rehabilitación y liberación de fauna silvestre. Reciben más de 1,500 casos de animales silvestres al año, desde animales encontrados en hogares hasta animales electrocutados en líneas eléctricas públicas. Su objetivo principal es devolver a los animales a la vida silvestre cuando están listos, pero aquellos que no pueden ser liberados se convierten en ''Embajadores de Educación'' a través de tours guiados. Ofrecen programas de voluntariado con alojamiento en la Casa Ewa, ubicada dentro de la propiedad del refugio, y brindan cuidado veterinario especializado. Su enfoque educativo busca enseñar a las futuras generaciones sobre el respeto a la vida silvestre y el equilibrio de la naturaleza.', 9.933429310124312, -84.16661819017118, 'https://www.refugioanimalcr.com'),
('jaguar-rescue-center', 'Jaguar Rescue Center', 'La misión del Jaguar Rescue Center es rescatar, rehabilitar y liberar animales silvestres de vuelta a su hábitat natural en áreas protegidas. Su objetivo principal es brindar cuidado veterinario especializado y atención continua a animales maltratados, heridos o confiscados, dándoles una segunda oportunidad de vida. Para aquellos animales que no pueden ser liberados, proporcionan un hogar permanente. Además, se enfocan en la educación y conservación, fomentando un mayor entendimiento y respeto por el delicado equilibrio del ecosistema costarricense entre locales y visitantes.', 'Puerto Viejo de Talamanca, Limón, Costa Rica', 'En la página', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/jaguar-center.jpg?alt=media&token=19bd2890-f79c-46c5-9133-e15932fa9b9e', 'Jaguar rescue center, limón', 'El Jaguar Rescue Center es un centro de rescate ubicado en Puerto Viejo de Talamanca, Playa Chiquita, que se dedica al rescate, rehabilitación y liberación de fauna silvestre. Fundado en 2008 por Encar García y Sandro Alviani, el centro ha rescatado aproximadamente 6,000 animales hasta la fecha. Se especializa en el cuidado de mamíferos, aves y reptiles, proporcionando servicios veterinarios y atención las 24 horas del día a animales que de otra manera no podrían sobrevivir en la selva tropical o el mar Caribe. Los visitantes pueden tener contacto directo con monos, felinos salvajes, perezosos, mapaches, osos hormigueros y otros animales durante tours educativos guiados. El centro también trabaja en la prevención de electrocuciones de animales silvestres mediante la instalación de puentes para fauna y aislamiento de líneas eléctricas peligrosas.', 9.642104672245608, -82.72358876133899, 'http://www.jaguarrescue.foundation'),
('parque-nacional-corcovado', 'Parque Nacional Corcovado', 'La misión del Parque Nacional Corcovado es conservar y proteger uno de los ecosistemas más biodiversos del planeta, preservando el bosque primario más grande en la costa del Pacífico de América Central. Su objetivo es mantener los 13 ecosistemas principales que alberga, desde bosques lluviosos tropicales hasta manglares, permitiendo el estudio científico de la estructura de los ecosistemas tropicales mientras se facilita el acceso controlado para actividades de ecoturismo educativo y observación de la vida silvestre, contribuyendo así a la conservación global de la biodiversidad.', 'Península de Osa, Puntarenas, Costa Rica', 'reservaciones.pnc@sinac.go.cr', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/paque-nacional-corcovado.webp?alt=media&token=dbd5a9a3-5def-46a2-8730-0de18ba69d92', 'Parque nacional corcovado, península de osa', 'El Parque Nacional Corcovado es un área silvestre protegida ubicada en la Península de Osa que alberga el 2.5% de la biodiversidad del planeta. Fue calificado por National Geographic como ''el lugar biológicamente más intenso de la Tierra en términos de biodiversidad''. Con 424 kilómetros cuadrados, es el parque nacional más grande de Costa Rica y protege alrededor de un tercio de la península de Osa. El parque protege 13 ecosistemas principales incluyendo bosque lluvioso tropical, bosque nuboso, bosque de palma jolillo y manglares. Es muy rico en fauna y flora, con unas 500 especies de árboles. Ofrece oportunidades únicas para estudiar la estructura de los ecosistemas tropicales y realizar actividades de ecoturismo, senderismo y observación de vida silvestre.', 8.54530445276679, -83.57185184457356, 'https://www.sinac.go.cr/es/ac/acosa/pnc/Paginas/default.aspx'),
('toucan-rescue-ranch', 'Toucan Rescue Ranch', 'La misión del Toucan Rescue Ranch es rescatar, rehabilitar y liberar fauna silvestre costarricense. Su objetivo es salvar la selva tropical, un animal a la vez, mediante un modelo poderoso enfocado en el rescate de animales de la selva tropical y el avance de la conservación a través de educación e investigación. Se dedican a avanzar en la medicina veterinaria para fauna silvestre, educar al público sobre conservación ambiental y liberar exitosamente animales rescatados en sus hábitats naturales, asegurando un futuro más brillante y saludable tanto para los animales como para nuestro planeta.', 'San Josecito de San Isidro, Heredia, Costa Rica', 'info@toucanrescueranch.org', 'https://firebasestorage.googleapis.com/v0/b/eco-explorer-be3cr.firebasestorage.app/o/tucan-rescue.png?alt=media&token=8cc578ac-77a7-40c9-a284-b3b575c79e38', 'Toucan Rescue Ranch', 'El Toucan Rescue Ranch es una instalación licenciada de rescate de vida silvestre ubicada en San Josecito de San Isidro, Heredia. Fundado hace más de una década por Leslie Howle y Jorge Murillo, comenzó rescatando tucanes heridos y enfermos y ahora opera como una organización sin fines de lucro 501(c)(3) en Estados Unidos y fundación reconocida en Costa Rica. Su modelo se enfoca en rescatar animales de la selva tropical y avanzar en la conservación a través de educación e investigación. Trabajan estrechamente con el Ministerio de Ambiente y Energía de Costa Rica (MINAE) recibiendo animales confiscados, enfermos y heridos. Ofrecen tours educativos en inglés y español, programas de voluntariado con experiencias prácticas, adopción simbólica de animales y se especializan en medicina veterinaria avanzada para fauna silvestre.', 10.025800675060081, -84.03518921900533, 'https://toucanrescueranch.org');

    